# MQTT Configuration
mp.messaging.incoming.data-in.connector=smallrye-mqtt
mp.messaging.incoming.data-in.topic=test/topic

mp.messaging.outgoing.data-out.connector=smallrye-mqtt
mp.messaging.outgoing.data-out.topic=test/topic

mp.messaging.incoming.test/topic.broadcast=true

quarkus.http.host=0.0.0.0
quarkus.http.port=9000

ca.client.addr.list=127.0.0.1
ca.client.auto.addr.list=NO