# MQTT Configuration
mp.messaging.incoming.data-in.connector=smallrye-mqtt
mp.messaging.incoming.data-in.topic=test/topic

mp.messaging.outgoing.data-out.connector=smallrye-mqtt
mp.messaging.outgoing.data-out.topic=test/topic

quarkus.http.host=0.0.0.0
quarkus.http.port=9000
