hosted:
#  - alias: hosted_test
#    mqttTopic: pv/hosted
#    protocol: ca
#    localNames:
#      ca: BL01T-EA-TST-02:UPTIME
#    access: READ_ONLY

external:
#  - alias: external_test
#    mqttTopic: pv/external
#    access: READ_WRITE
